const shared = {
  requirements: "Apple Silicon · macOS 15+",
  githubUrl: "https://github.com/bigmacfive/ulpaso",
};

export const SITE_COPY = {
  en: {
    ...shared,
    language: "Language",
    download: "Free download for Mac",
    github: "View on GitHub",
    landing: {
      heroLine1: "Meetings stay on your Mac. Notes stay in Markdown.",
      heroLine2: "No account or subscription required. Every record stays on your Mac.",
      section1Label: "ON-DEVICE MARKDOWN",
      section1Title: "Your thoughts, on your Mac.",
      section1Body: "Capture ideas and meetings in familiar Markdown files.\nNo account or separate cloud storage required.",
      stepsAria: "How Ulpaso works",
      steps: [
        ["Create a document", "Start a Markdown document and save it directly to any folder you choose."],
        ["Capture a meeting", "Transcribe meeting audio on-device and organize it into a Markdown document."],
        ["Keep writing", "Find what you need quickly and carry it naturally into your next document."],
      ],
      section2Label: "DATA THAT STAYS ON YOUR MAC",
      features: [
        ["Markdown documents", "Every .md file stays on your Mac and opens normally in any other editor."],
        ["Meeting audio and transcripts", "Audio and transcripts are processed on-device and are never sent to an external server."],
        ["Settings and search index", "App settings and the search index stay local too. No account or cloud service required."],
      ],
      section3Label: "MEETING NOTES: BEFORE → AFTER",
      waveformAlt: "Waveform representing meeting audio",
      before: "BEFORE",
      beforeCaption: "Conversation as spoken",
      beforeLines: [
        ["00:00", "Minji", "Let's start by reviewing this quarter's roadmap."],
        ["00:18", "Soyeon", "I think we should improve the onboarding flow first."],
        ["00:32", "Taeyoon", "Let's also look at search speed and tags."],
        ["00:48", "Minji", "Great. We'll review progress item by item next week."],
      ],
      after: "AFTER",
      afterCaption: "Organized Markdown note",
      afterTitle: "## Next-quarter roadmap meeting",
      afterDecision: "### Key decisions",
      afterDecisionItems: ["Improve onboarding", "Improve search speed", "Clarify the tag flow"],
      afterNext: "### Next steps",
      afterNextItems: ["[ ] Apply user feedback", "[ ] Review progress next week"],
      section4Label: "OPEN SOURCE & CONTRIBUTING",
      principlesAria: "Open-source principles",
      principles: [
        ["Free and open source", "Use Ulpaso for free. Every line of code is available under the MIT License."],
        ["Build a better tool together", "Issues, ideas, and improvements are always welcome."],
        ["A system you can inspect", "Anyone can review how data flows through the actual implementation."],
      ],
      section5Label: "RUN FROM SOURCE",
      section5Title: "Run Ulpaso from source.",
      section5Body: "Clone the repository, prepare the development environment,\nand run it directly on your Mac.",
      githubRepository: "View the GitHub repository",
      terminalAria: "Commands for running Ulpaso",
      terminalTitle: "Run in Terminal",
      copy: "Copy commands",
      copied: "Copied",
      section6Label: "READY TO TRY ULPASO?",
      section6Title: "Start Ulpaso on your Mac.",
    },
    footer: {
      navAria: "Legal and service documents",
      privacy: "Privacy",
      terms: "Terms",
      license: "MIT License",
      operatedBy: "Operated by askitmore co., ltd",
    },
    demo: {
      aria: "Automatic transcription demo based on the actual Ulpaso app",
      meetingTitle: "Meeting notes · 2026-08-12 14:30",
      untitled: "Untitled *",
      transcribing: "Transcribing",
      sidebar: "Open sidebar",
      settings: "Settings",
      meeting: "Meeting notes",
      listening: "Listening…",
      organizing: "Organizing speakers…",
      speaker: "Speaker",
      meetingLines: [
        [1, "Let's begin by simplifying the onboarding flow for this sprint."],
        [2, "We should incorporate user feedback and make the search entry point easier to find."],
        [3, "Let's improve search performance too and review the results next week."],
        [1, "Great. Please leave the owners and next steps in the note."],
      ],
      slashAria: "Formatting commands",
      slashItems: ["Start meeting notes", "Heading 1", "Heading 2", "Heading 3", "Blockquote", "Code block", "Divider", "Image", "Table", "Bulleted list", "Numbered list", "Task list"],
    },
    legal: {
      back: "Overview",
      navAria: "Legal documents",
      nav: ["Operator", "Privacy", "Terms"],
      updated: "Last updated",
      updatedDate: "August 15, 2026",
      pages: {
        legal: ["OPERATOR & LEGAL", "Operator and legal information", "Who operates Ulpaso, the principles behind it, and the licenses and policies that apply."],
        privacy: ["PRIVACY POLICY", "Privacy policy", "How the Ulpaso app and website handle data and protect your privacy."],
        terms: ["TERMS OF USE", "Terms of use", "The basic terms that apply when you use the Ulpaso software and website."],
      },
      overview: {
        operatorTitle: "Operator",
        facts: [["Legal name", "askitmore co., ltd"], ["Brand", "askitmore"], ["Representative", "Minkyu Lee"], ["Service", "Ulpaso"], ["Contact", "support@askitmore.com"], ["Address", "117 Seoulsiripdae-ro, Dongdaemun-gu, Seoul, Republic of Korea"]],
        operatorBody: "askitmore co., ltd operates the Ulpaso website and distribution information. Ulpaso is a local Markdown editor for macOS that does not require an account or cloud storage.",
        docsTitle: "Documents",
        cards: [["01", "Privacy policy", "How local files, meeting audio, and website access data are handled"], ["02", "Terms of use", "Software use, recording responsibilities, disclaimers, and governing law"], ["03", "MIT License", "Terms for using, copying, modifying, and distributing the open-source code"], ["04", "Third-party notices", "Licenses for the editor, fonts, models, and dependencies"]],
        openTitle: "Open-source principles",
        openBody: "Ulpaso's source code is available under the MIT License. You can review the implementation, open an issue, or propose a change in the repository. Third-party software, models, and fonts included with Ulpaso remain subject to their respective authors' licenses.",
        repo: "GitHub repository",
        fontTitle: "Font licensing",
        fontBody: "Goorm Sans, provided by goorm, is used for body text. HanYongUn, created for the GS Caltex Independence Typeface Campaign, appears only in short handwritten passages and is credited in accordance with its attribution guidance.",
        fontLink: "Review the HanYongUn license",
      },
      privacySections: [
        { title: "1. Scope and operator", paragraphs: ["This policy applies to the Ulpaso website and macOS application operated by askitmore co., ltd. Send privacy questions to support@askitmore.com."] },
        { highlight: "Your notes stay on your Mac.", title: "2. Information the app does not collect", paragraphs: ["Ulpaso does not operate user accounts, advertising, usage analytics, behavioral profiling, or app telemetry. Markdown documents, meeting audio, and transcripts are not sent to servers operated by askitmore co., ltd."] },
        { title: "3. Information processed on-device", bullets: [["Documents", "Markdown files remain in the location you choose. Recent file paths and recovery drafts may be stored on-device."], ["Meeting audio", "Microphone and system audio are processed on-device. Temporary recovery files are deleted after a successful transcription or cancellation, but may remain after an unexpected shutdown so your work can be recovered."], ["Permissions", "Screen Recording permission is used only to capture system audio through ScreenCaptureKit. Ulpaso does not store video frames of your screen."], ["Deletion", "Deleting the app data folder removes runtimes, models, and recovery data. Markdown files saved elsewhere must be deleted by you."]] },
        { title: "4. Network connections and external services", paragraphs: ["Ulpaso may connect to GitHub to check for and distribute updates, and to Hugging Face to download transcription runtimes and models. These requests do not include document content, meeting audio, or transcripts. Each provider may process ordinary connection data, such as IP address and request time, under its own policy."] },
        { title: "5. Website and support information", paragraphs: ["The website hosting provider may temporarily process technical access data—such as IP address, browser, operating system, requested URL, and time—to deliver and secure the site. askitmore co., ltd does not use non-essential analytics cookies or advertising trackers on the Ulpaso website.", "When you contact us by email, we process your email address and message to respond. We delete the information without undue delay after resolving the inquiry unless retention is required by law or reasonably necessary to address a dispute."] },
        { title: "6. Disclosure, processors, and safeguards", paragraphs: ["We do not sell personal information or disclose it for advertising. Technical providers may process limited data where necessary to host and distribute the service. askitmore co., ltd applies reasonable safeguards, including access controls and up-to-date software."] },
        { title: "7. Your rights", paragraphs: ["You may request access, correction, deletion, or restriction of information about you. Most app data can be managed directly on your Mac. For website or support-related requests, contact support@askitmore.com."] },
        { title: "8. Changes and effective date", paragraphs: ["We may update this policy to reflect changes to the service or applicable law. Material changes will be posted on this page with an effective date. This policy is effective August 12, 2026."] },
      ],
      termsSections: [
        { title: "1. Operator and application of these terms", paragraphs: ["These terms apply to the Ulpaso website, download information, and related features provided by askitmore co., ltd. By downloading or using Ulpaso, you agree to these terms and the applicable open-source licenses."] },
        { title: "2. Open-source software", paragraphs: ["Ulpaso source code is provided under the MIT License. You may use, copy, modify, and distribute the code as permitted by that license. Separate licenses for third-party components take precedence for those components."] },
        { title: "3. Lawful use", paragraphs: ["You must comply with applicable law and may not infringe the rights of others or interfere with the service. You may not use Ulpaso to distribute malware, gain unauthorized access, or violate another person's privacy or copyright."] },
        { highlight: "Respect the people in the room before you record.", title: "4. Responsibility for recording and transcription", paragraphs: ["Before recording or transcribing a meeting, confirm the laws that apply to notice, consent, communications privacy, personal information, and employment. The person who starts a recording is responsible for obtaining any required permission and for lawful use and retention of the result."] },
        { title: "5. Files and backups", paragraphs: ["Ulpaso works with local files. You are responsible for backups, storage locations, device security, and access permissions. Back up important data before updating the app or changing your environment."] },
        { title: "6. Disclaimer and limitation of liability", paragraphs: ["To the fullest extent permitted by law, Ulpaso is provided as is. We do not warrant fitness for a particular purpose, error-free operation, or uninterrupted availability. Unless caused by intent or gross negligence, askitmore co., ltd is not liable for indirect loss arising from use, data loss, or third-party services."] },
        { title: "7. Changes and discontinuation", paragraphs: ["We may change or discontinue the website or distribution method for security, product improvement, or operational reasons. Material changes to these terms will be posted on this page with an effective date."] },
        { title: "8. Governing law and contact", paragraphs: ["These terms are governed by the laws of the Republic of Korea. Disputes will be resolved by a court with jurisdiction under applicable law. Contact support@askitmore.com with questions. These terms are effective August 12, 2026."] },
      ],
    },
  },
  ko: {
    ...shared,
    language: "언어",
    download: "Mac용 무료 다운로드",
    github: "GitHub에서 보기",
    landing: {
      heroLine1: "회의는 Mac에서, 기록은 Markdown으로.", heroLine2: "계정도 결제도 필요 없습니다. 모든 기록은 당신의 Mac에만 남습니다.",
      section1Label: "ON-DEVICE MARKDOWN", section1Title: "당신의 생각은, 당신의 Mac에.", section1Body: "익숙한 Markdown 파일에 생각과 회의 내용을 담으세요.\n계정도 별도의 클라우드 공간도 필요하지 않습니다.", stepsAria: "Ulpaso 사용 순서",
      steps: [["문서 만들기", "새 Markdown 문서를 만들면 원하는 폴더에 바로 저장됩니다."], ["회의 기록하기", "회의 음성을 기기 안에서 전사하고 Markdown 문서로 정리합니다."], ["내용 이어 쓰기", "필요한 내용을 빠르게 찾아 다음 문서에 자연스럽게 이어 쓰세요."]],
      section2Label: "Mac에 남는 데이터", features: [["Markdown 문서", "모든 .md 파일은 당신의 Mac에 저장되며 다른 편집기에서도 그대로 열 수 있습니다."], ["회의 녹음과 전사문", "녹음 파일과 전사문은 기기 안에서 처리되며 외부 서버로 전송되지 않습니다."], ["설정과 검색 색인", "앱 설정과 검색 색인도 로컬에만 저장됩니다. 계정이나 클라우드는 필요하지 않습니다."]],
      section3Label: "회의 기록: BEFORE → AFTER", waveformAlt: "회의 음성을 이미지로 표현한 파형", before: "BEFORE", beforeCaption: "대화 그대로", beforeLines: [["00:00", "민지", "이번 분기 로드맵부터 정리해 볼게요."], ["00:18", "수연", "온보딩 흐름을 먼저 다듬으면 좋겠어요."], ["00:32", "태윤", "검색 속도와 태그 기능도 함께 살펴보죠."], ["00:48", "민지", "좋아요. 다음 주에 항목별 진행 상황을 확인할게요."]], after: "AFTER", afterCaption: "정리된 Markdown 노트", afterTitle: "## 다음 분기 로드맵 회의", afterDecision: "### 핵심 결정", afterDecisionItems: ["온보딩 경험 개선", "검색 속도 개선", "태그 흐름 정리"], afterNext: "### 다음 단계", afterNextItems: ["[ ] 피드백 반영", "[ ] 다음 주 진행 상황 확인"],
      section4Label: "오픈소스와 기여", principlesAria: "오픈소스 원칙", principles: [["무료 오픈소스", "누구나 무료로 사용할 수 있으며 모든 코드는 MIT 라이선스로 공개됩니다."], ["함께 만드는 더 나은 도구", "이슈와 제안, 기능 개선을 언제든 환영합니다."], ["직접 확인할 수 있는 구조", "데이터의 흐름과 실제 구현을 누구나 확인할 수 있습니다."]],
      section5Label: "소스에서 실행하기", section5Title: "소스에서 Ulpaso를 직접 실행하세요.", section5Body: "저장소를 내려받아 개발 환경을 준비하고\n당신의 Mac에서 바로 실행할 수 있습니다.", githubRepository: "GitHub 저장소 보기", terminalAria: "Ulpaso 설치 명령", terminalTitle: "터미널에서 실행", copy: "명령 복사", copied: "복사됨", section6Label: "Ulpaso를 시작해 볼까요?", section6Title: "당신의 Mac에서 Ulpaso를 시작하세요.",
    },
    footer: { navAria: "법률 및 운영 문서", privacy: "개인정보처리방침", terms: "이용약관", license: "MIT 라이선스", operatedBy: "askitmore co., ltd 운영" },
    demo: { aria: "실제 Ulpaso 앱 구조로 만든 자동 전사 데모", meetingTitle: "회의 기록 · 2026-08-12 14:30", untitled: "제목 없음 *", transcribing: "전사 중", sidebar: "사이드바 열기", settings: "설정", meeting: "회의 기록", listening: "듣는 중…", organizing: "화자 정리 중…", speaker: "Speaker", meetingLines: [[1, "이번 스프린트에서는 온보딩 흐름부터 정리해 볼게요."], [2, "사용자 피드백을 반영하고 검색 진입점을 단순하게 만들면 좋겠어요."], [3, "검색 속도 개선도 함께 진행하고 다음 주에 결과를 확인하죠."], [1, "좋아요. 담당 항목과 다음 단계를 노트에 남겨 주세요."]], slashAria: "서식 명령 목록", slashItems: ["회의 기록 시작", "제목 1", "제목 2", "제목 3", "인용문", "코드 블록", "구분선", "이미지", "표", "글머리 기호 목록", "번호 목록", "할 일 목록"] },
    legal: null,
  },
  ja: {
    ...shared,
    language: "言語",
    download: "Mac版を無料ダウンロード",
    github: "GitHubで見る",
    landing: {
      heroLine1: "会議はMacで。記録はMarkdownで。", heroLine2: "アカウントも支払いも不要です。すべての記録はあなたのMacにだけ残ります。",
      section1Label: "ON-DEVICE MARKDOWN", section1Title: "あなたの思考を、あなたのMacに。", section1Body: "使い慣れたMarkdownファイルに、アイデアや会議の内容を残せます。\nアカウントも別のクラウド領域も必要ありません。", stepsAria: "Ulpasoの使い方",
      steps: [["文書を作成", "新しいMarkdown文書を作ると、選んだフォルダにそのまま保存されます。"], ["会議を記録", "会議音声をデバイス内で文字起こしし、Markdown文書として整理します。"], ["続きを書く", "必要な内容をすぐに見つけ、次の文書へ自然につなげられます。"]],
      section2Label: "MACに残るデータ", features: [["Markdown文書", "すべての.mdファイルはMacに保存され、ほかのエディターでもそのまま開けます。"], ["会議音声と文字起こし", "録音と文字起こしはデバイス内で処理され、外部サーバーへ送信されません。"], ["設定と検索インデックス", "アプリ設定と検索インデックスもローカルにのみ保存されます。アカウントやクラウドは不要です。"]],
      section3Label: "会議メモ：BEFORE → AFTER", waveformAlt: "会議音声を表す波形", before: "BEFORE", beforeCaption: "会話をそのまま", beforeLines: [["00:00", "ミンジ", "今四半期のロードマップから整理しましょう。"], ["00:18", "スヨン", "まずオンボーディングの流れを改善したいです。"], ["00:32", "テユン", "検索速度とタグ機能も一緒に見直しましょう。"], ["00:48", "ミンジ", "いいですね。来週、項目ごとの進捗を確認します。"]], after: "AFTER", afterCaption: "整理されたMarkdownノート", afterTitle: "## 次四半期ロードマップ会議", afterDecision: "### 主な決定", afterDecisionItems: ["オンボーディング体験の改善", "検索速度の改善", "タグ導線の整理"], afterNext: "### 次のステップ", afterNextItems: ["[ ] フィードバックを反映", "[ ] 来週進捗を確認"],
      section4Label: "オープンソースと貢献", principlesAria: "オープンソースの原則", principles: [["無料のオープンソース", "誰でも無料で利用でき、すべてのコードをMITライセンスで公開しています。"], ["一緒に育てる、より良い道具", "Issue、提案、機能改善をいつでも歓迎します。"], ["自分で確かめられる仕組み", "データの流れと実装を誰でも確認できます。"]],
      section5Label: "ソースから実行", section5Title: "ソースからUlpasoを実行できます。", section5Body: "リポジトリをクローンして開発環境を整え、\nあなたのMacで直接実行できます。", githubRepository: "GitHubリポジトリを見る", terminalAria: "Ulpasoの実行コマンド", terminalTitle: "ターミナルで実行", copy: "コマンドをコピー", copied: "コピーしました", section6Label: "ULPASOを始めませんか？", section6Title: "あなたのMacでUlpasoを始めましょう。",
    },
    footer: { navAria: "法務・運営文書", privacy: "プライバシー", terms: "利用規約", license: "MITライセンス", operatedBy: "運営 askitmore co., ltd" },
    demo: { aria: "実際のUlpasoアプリを再現した自動文字起こしデモ", meetingTitle: "会議メモ · 2026-08-12 14:30", untitled: "無題 *", transcribing: "文字起こし中", sidebar: "サイドバーを開く", settings: "設定", meeting: "会議メモ", listening: "聞き取り中…", organizing: "話者を整理中…", speaker: "Speaker", meetingLines: [[1, "このスプリントでは、まずオンボーディングの流れを整理しましょう。"], [2, "ユーザーの意見を反映し、検索の入口をもっと分かりやすくしたいです。"], [3, "検索速度も改善して、来週結果を確認しましょう。"], [1, "いいですね。担当者と次のステップをノートに残してください。"]], slashAria: "書式コマンド一覧", slashItems: ["会議メモを開始", "見出し1", "見出し2", "見出し3", "引用", "コードブロック", "区切り線", "画像", "表", "箇条書き", "番号付きリスト", "タスクリスト"] },
    legal: null,
  },
};

SITE_COPY.ko.legal = {
  ...SITE_COPY.en.legal,
  back: "소개 페이지", navAria: "법률 문서", nav: ["운영 안내", "개인정보 처리방침", "이용약관"], updated: "최종 업데이트", updatedDate: "2026년 8월 15일",
  pages: { legal: ["OPERATOR & LEGAL", "운영 및 법률 안내", "Ulpaso를 누가 운영하고, 어떤 원칙과 라이선스로 제공하는지 한곳에 정리했습니다."], privacy: ["PRIVACY POLICY", "개인정보 처리방침", "Ulpaso 앱과 소개 웹사이트에서 데이터가 어떻게 처리되는지 설명합니다."], terms: ["TERMS OF USE", "이용약관", "Ulpaso 소프트웨어와 소개 웹사이트를 이용할 때 적용되는 기본 조건입니다."] },
  overview: { operatorTitle: "운영 주체", facts: [["법인명", "askitmore co., ltd"], ["브랜드", "askitmore"], ["대표", "Minkyu Lee"], ["서비스", "Ulpaso"], ["문의", "support@askitmore.com"], ["주소", "서울특별시 동대문구 서울시립대로 117"]], operatorBody: "askitmore co., ltd는 Ulpaso 소개 웹사이트와 배포 안내를 운영합니다. Ulpaso는 계정과 클라우드 저장을 요구하지 않는 macOS용 로컬 Markdown 편집기입니다.", docsTitle: "문서 바로가기", cards: [["01", "개인정보 처리방침", "로컬 파일, 회의 오디오, 웹사이트 접속 정보의 처리 방식"], ["02", "이용약관", "소프트웨어 이용, 녹음 책임, 면책과 준거법"], ["03", "MIT 라이선스", "오픈소스 코드의 이용·복제·수정·배포 조건"], ["04", "제3자 고지", "편집기, 글꼴, 모델과 의존성의 개별 라이선스"]], openTitle: "오픈소스 원칙", openBody: "Ulpaso의 소스 코드는 MIT 라이선스로 공개됩니다. 저장소에서 구현을 검토하고, 이슈를 남기거나, 변경을 제안할 수 있습니다. 함께 배포되는 제3자 소프트웨어·모델·글꼴에는 각각의 원 저작자 라이선스가 적용됩니다.", repo: "GitHub 저장소", fontTitle: "글꼴 이용 안내", fontBody: "본문에는 구름이 제공하는 Goorm Sans를 사용합니다. 짧은 손글씨 표현에는 GS칼텍스 독립서체 캠페인의 한용운체를 사용하며, 출처 표기 권고에 따라 제작자를 함께 밝힙니다.", fontLink: "한용운체 이용 범위 확인" },
  privacySections: [
    { title: "1. 적용 범위와 운영자", paragraphs: ["이 방침은 askitmore co., ltd가 운영하는 Ulpaso 소개 웹사이트와 Ulpaso macOS 애플리케이션에 적용됩니다. 개인정보 관련 문의는 support@askitmore.com으로 보내실 수 있습니다."] },
    { highlight: "당신의 노트는 당신의 Mac에 남습니다.", title: "2. 앱에서 수집하지 않는 정보", paragraphs: ["Ulpaso는 회원 계정, 광고, 사용 분석, 행동 프로파일링 또는 앱 원격 측정 기능을 운영하지 않습니다. 사용자가 연 Markdown 문서의 내용, 회의 오디오와 전사 결과는 askitmore co., ltd가 운영하는 서버로 전송되지 않습니다."] },
    { title: "3. 기기 안에서 처리되는 정보", bullets: [["문서", "사용자가 선택한 Markdown 파일은 원래 저장 위치에 남습니다. 최근 파일 경로와 복구 초안은 기기 안에 보관될 수 있습니다."], ["회의 오디오", "마이크 및 시스템 오디오는 기기 안에서 처리됩니다. 임시 복구 파일은 정상 전사 또는 취소 후 삭제되며, 예기치 않은 종료 시 복구를 위해 남을 수 있습니다."], ["권한", "화면 기록 권한은 ScreenCaptureKit을 통한 시스템 오디오 입력에만 사용되며 화면 영상 프레임을 저장하지 않습니다."], ["삭제", "앱 데이터 폴더를 삭제하면 런타임, 모델과 복구 데이터를 제거할 수 있습니다. 별도 위치에 저장한 Markdown 파일은 사용자가 직접 삭제해야 합니다."]] },
    { title: "4. 네트워크 연결과 외부 서비스", paragraphs: ["Ulpaso는 앱 업데이트 확인과 배포를 위해 GitHub에 연결하고, 전사 런타임 및 모델 다운로드를 위해 Hugging Face에 연결할 수 있습니다. 이 요청에 문서 내용, 회의 오디오 또는 전사문을 포함하지 않습니다. 각 서비스는 접속 과정에서 IP 주소·요청 시각 등 통상적인 연결 정보를 자체 방침에 따라 처리할 수 있습니다."] },
    { title: "5. 웹사이트와 문의 정보", paragraphs: ["소개 웹사이트의 호스팅 제공자는 페이지 전송과 보안을 위해 IP 주소, 브라우저·운영체제 정보, 요청 URL과 시각 같은 기술적 접속 정보를 일시 처리할 수 있습니다. askitmore co., ltd는 Ulpaso 소개 웹사이트에서 비필수 분석 쿠키나 광고 추적기를 사용하지 않습니다.", "이메일로 문의하면 답변을 위해 발신 이메일 주소와 문의 내용을 처리합니다. 문의가 해결된 뒤 지체 없이 삭제하되, 관계 법령상 보관 의무나 분쟁 대응 필요가 있는 경우 해당 기간 동안 보관할 수 있습니다."] },
    { title: "6. 제공, 위탁과 안전조치", paragraphs: ["개인정보를 판매하거나 광고 목적으로 제공하지 않습니다. 웹 호스팅·배포 등 서비스 제공에 필요한 기술 사업자가 제한된 범위에서 정보를 처리할 수 있으며, askitmore co., ltd는 합리적인 접근 통제와 최신 소프트웨어 유지 등 안전조치를 적용합니다."] },
    { title: "7. 이용자의 권리", paragraphs: ["본인 정보에 대한 열람, 정정, 삭제 또는 처리 제한을 요청할 수 있습니다. 대부분의 앱 데이터는 사용자의 Mac에서 직접 관리할 수 있으며, 웹사이트 또는 문의와 관련된 요청은 support@askitmore.com으로 접수합니다."] },
    { title: "8. 변경과 시행", paragraphs: ["서비스나 법령 변경을 반영하기 위해 이 방침을 수정할 수 있습니다. 중요한 변경은 이 페이지에 시행일과 함께 알립니다. 이 방침은 2026년 8월 12일부터 시행합니다."] },
  ],
  termsSections: [
    { title: "1. 운영자와 약관의 적용", paragraphs: ["이 약관은 askitmore co., ltd가 제공하는 Ulpaso 소개 웹사이트, 다운로드 안내와 관련 기능에 적용됩니다. Ulpaso를 내려받거나 사용하면 이 약관과 적용되는 오픈소스 라이선스에 동의한 것으로 봅니다."] },
    { title: "2. 오픈소스 소프트웨어", paragraphs: ["Ulpaso 소스 코드는 MIT 라이선스에 따라 제공됩니다. 이용자는 해당 라이선스가 허용하는 범위에서 코드를 사용, 복제, 수정 및 배포할 수 있습니다. 제3자 구성요소에는 각 구성요소의 별도 라이선스가 우선 적용됩니다."] },
    { title: "3. 적법한 이용", paragraphs: ["이용자는 관련 법령을 준수하고 타인의 권리나 서비스의 안정성을 침해하지 않아야 합니다. 악성코드 배포, 불법 접근, 제3자의 개인정보나 저작권을 침해하는 방식으로 서비스를 이용할 수 없습니다."] },
    { highlight: "기록하기 전에, 함께 있는 사람을 존중해 주세요.", title: "4. 회의 녹음과 전사의 책임", paragraphs: ["녹음·전사 기능을 사용할 때에는 참여자 고지와 동의를 포함해 적용되는 통신비밀, 개인정보 및 노동 관련 법령을 확인해야 합니다. 녹음 권한과 결과물의 적법한 이용·보관에 대한 책임은 기능을 실행한 이용자에게 있습니다."] },
    { title: "5. 파일과 백업", paragraphs: ["Ulpaso는 로컬 파일을 다루는 도구입니다. 중요한 파일의 백업, 저장 위치 관리, 기기 보안과 접근 권한 관리는 이용자의 책임입니다. 업데이트나 환경 변경 전에는 필요한 자료를 별도로 백업해 주세요."] },
    { title: "6. 보증과 책임의 제한", paragraphs: ["Ulpaso는 적용 법률이 허용하는 최대 범위에서 현재 상태로 제공됩니다. 특정 목적 적합성, 오류 없는 동작 또는 항상 지속되는 제공을 보증하지 않습니다. askitmore co., ltd는 고의 또는 중대한 과실이 없는 한 이용자의 사용, 데이터 손실 또는 제3자 서비스에서 발생한 간접 손해에 책임을 지지 않습니다."] },
    { title: "7. 변경과 중단", paragraphs: ["보안, 기능 개선 또는 운영상 필요에 따라 웹사이트와 배포 방식을 변경하거나 중단할 수 있습니다. 약관을 중요하게 변경하는 경우 이 페이지에 시행일과 함께 안내합니다."] },
    { title: "8. 준거법과 문의", paragraphs: ["이 약관은 대한민국 법률에 따라 해석합니다. 분쟁이 발생하면 관계 법령상 관할 법원에서 해결합니다. 문의는 support@askitmore.com으로 보내주세요. 이 약관은 2026년 8월 12일부터 시행합니다."] },
  ],
};

SITE_COPY.ja.legal = {
  ...SITE_COPY.en.legal,
  back: "紹介ページ", navAria: "法務文書", nav: ["運営情報", "プライバシー", "利用規約"], updated: "最終更新", updatedDate: "2026年8月15日",
  pages: { legal: ["OPERATOR & LEGAL", "運営・法務情報", "Ulpasoの運営者、提供方針、適用されるライセンスとポリシーをご案内します。"], privacy: ["PRIVACY POLICY", "プライバシーポリシー", "Ulpasoアプリとウェブサイトにおけるデータの取り扱いを説明します。"], terms: ["TERMS OF USE", "利用規約", "Ulpasoソフトウェアとウェブサイトを利用する際の基本条件です。"] },
  overview: { operatorTitle: "運営者", facts: [["法人名", "askitmore co., ltd"], ["ブランド", "askitmore"], ["代表", "Minkyu Lee"], ["サービス", "Ulpaso"], ["お問い合わせ", "support@askitmore.com"], ["住所", "大韓民国 ソウル特別市 東大門区 ソウル市立大路117"]], operatorBody: "askitmore co., ltdはUlpasoの紹介サイトと配布情報を運営しています。Ulpasoはアカウントやクラウド保存を必要としない、macOS向けのローカルMarkdownエディターです。", docsTitle: "文書一覧", cards: [["01", "プライバシーポリシー", "ローカルファイル、会議音声、ウェブサイトアクセス情報の取り扱い"], ["02", "利用規約", "ソフトウェア利用、録音の責任、免責、準拠法"], ["03", "MITライセンス", "オープンソースコードの利用・複製・変更・配布条件"], ["04", "第三者通知", "エディター、フォント、モデル、依存関係の各ライセンス"]], openTitle: "オープンソースの原則", openBody: "UlpasoのソースコードはMITライセンスで公開されています。リポジトリで実装を確認し、Issueや変更提案を送れます。同梱する第三者ソフトウェア、モデル、フォントには、それぞれの作者のライセンスが適用されます。", repo: "GitHubリポジトリ", fontTitle: "フォントライセンス", fontBody: "本文にはgoorm提供のGoorm Sansを使用します。短い手書き表現にはGS Caltex独立書体キャンペーンのHanYongUnを使用し、推奨に従って制作者を表示します。", fontLink: "HanYongUnの利用範囲を確認" },
  privacySections: [
    { title: "1. 適用範囲と運営者", paragraphs: ["本ポリシーはaskitmore co., ltdが運営するUlpasoウェブサイトとmacOSアプリに適用されます。プライバシーに関するお問い合わせはsupport@askitmore.comへお送りください。"] },
    { highlight: "あなたのノートは、あなたのMacに残ります。", title: "2. アプリが収集しない情報", paragraphs: ["Ulpasoはユーザーアカウント、広告、利用分析、行動プロファイリング、アプリのテレメトリーを運用しません。Markdown文書、会議音声、文字起こしはaskitmore co., ltdのサーバーへ送信されません。"] },
    { title: "3. デバイス内で処理する情報", bullets: [["文書", "Markdownファイルは選択した場所に残ります。最近使ったファイルのパスや復旧用下書きはデバイス内に保存される場合があります。"], ["会議音声", "マイクとシステム音声はデバイス内で処理されます。復旧用の一時ファイルは正常終了またはキャンセル後に削除されますが、予期しない終了時には復旧のため残る場合があります。"], ["権限", "画面収録権限はScreenCaptureKitによるシステム音声入力にのみ使用し、画面の映像フレームは保存しません。"], ["削除", "アプリデータフォルダを削除すると、ランタイム、モデル、復旧データを削除できます。別の場所に保存したMarkdownファイルはご自身で削除してください。"]] },
    { title: "4. ネットワーク接続と外部サービス", paragraphs: ["Ulpasoはアップデート確認と配布のためGitHubへ、文字起こしランタイムとモデルのダウンロードのためHugging Faceへ接続する場合があります。文書内容、会議音声、文字起こしはこれらのリクエストに含まれません。各サービスはIPアドレスやリクエスト時刻など通常の接続情報を各自のポリシーに従って処理する場合があります。"] },
    { title: "5. ウェブサイトとお問い合わせ情報", paragraphs: ["ホスティング事業者はサイトの配信と保護のため、IPアドレス、ブラウザー、OS、URL、時刻などの技術的アクセス情報を一時的に処理する場合があります。askitmore co., ltdはUlpasoサイトで不要な分析Cookieや広告トラッカーを使用しません。", "メールでお問い合わせいただいた場合、返信のため送信元アドレスと内容を処理します。法令上の保存義務または紛争対応の必要がない限り、解決後遅滞なく削除します。"] },
    { title: "6. 提供、委託、安全管理", paragraphs: ["個人情報を販売したり広告目的で提供したりしません。ホスティングや配布に必要な技術事業者が限定的に処理する場合があります。askitmore co., ltdはアクセス制御や最新ソフトウェアの維持など合理的な安全措置を講じます。"] },
    { title: "7. 利用者の権利", paragraphs: ["ご本人の情報について、開示、訂正、削除、処理制限を求めることができます。多くのアプリデータはMac上で直接管理できます。ウェブサイトやお問い合わせに関する請求はsupport@askitmore.comへご連絡ください。"] },
    { title: "8. 変更と施行日", paragraphs: ["サービスや法令の変更に応じて本ポリシーを改定する場合があります。重要な変更は施行日とともにこのページでお知らせします。本ポリシーは2026年8月12日から施行します。"] },
  ],
  termsSections: [
    { title: "1. 運営者と規約の適用", paragraphs: ["本規約はaskitmore co., ltdが提供するUlpasoウェブサイト、ダウンロード案内、関連機能に適用されます。Ulpasoをダウンロードまたは利用すると、本規約と適用されるオープンソースライセンスに同意したものとみなします。"] },
    { title: "2. オープンソースソフトウェア", paragraphs: ["UlpasoのソースコードはMITライセンスに基づいて提供されます。同ライセンスの範囲で利用、複製、変更、配布できます。第三者コンポーネントには各コンポーネントの個別ライセンスが優先して適用されます。"] },
    { title: "3. 適法な利用", paragraphs: ["利用者は関係法令を守り、他者の権利やサービスの安定性を侵害してはなりません。マルウェアの配布、不正アクセス、第三者のプライバシーや著作権を侵害する目的で利用できません。"] },
    { highlight: "記録する前に、その場にいる人を尊重してください。", title: "4. 会議録音と文字起こしの責任", paragraphs: ["録音・文字起こしを行う前に、参加者への通知と同意を含め、通信の秘密、個人情報、労働に関する適用法令を確認してください。必要な許可の取得と結果の適法な利用・保管は、機能を実行した利用者の責任です。"] },
    { title: "5. ファイルとバックアップ", paragraphs: ["Ulpasoはローカルファイルを扱う道具です。重要ファイルのバックアップ、保存場所、デバイスの安全、アクセス権限は利用者が管理してください。更新や環境変更の前に必要なデータをバックアップしてください。"] },
    { title: "6. 保証と責任の制限", paragraphs: ["適用法令が認める最大限の範囲で、Ulpasoは現状のまま提供されます。特定目的への適合、無欠陥の動作、継続的な提供を保証しません。故意または重大な過失がない限り、askitmore co., ltdは利用、データ損失、第三者サービスから生じる間接損害について責任を負いません。"] },
    { title: "7. 変更と終了", paragraphs: ["セキュリティ、機能改善、運営上の必要により、ウェブサイトや配布方法を変更または終了する場合があります。重要な規約変更は施行日とともにこのページでお知らせします。"] },
    { title: "8. 準拠法とお問い合わせ", paragraphs: ["本規約は大韓民国法に準拠します。紛争は関係法令に基づく管轄裁判所で解決します。お問い合わせはsupport@askitmore.comへお送りください。本規約は2026年8月12日から施行します。"] },
  ],
};
